name       : python-openpyxl
version    : 3.0.9
release    : 5
homepage   : https://foss.heptapod.net/openpyxl
source     :
    - https://foss.heptapod.net/openpyxl/openpyxl/-/archive/3.0.9/openpyxl-3.0.9.tar.gz : 2277c5dfba58e8ea360154fb320b5497e41a11a2a6124a49c7d741a9119ae762
license    : MIT
component  : programming.python
summary    : openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
description: |
    openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
builddeps  :
    - pkgconfig(python3)
    - python-et_xmlfile
    - python-jdcal
    - python-lxml
    - python-pillow
    - python-pytest
rundeps    :
    - python-et_xmlfile
    - python-jdcal
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
