name       : python-openpyxl
version    : 3.0.10
release    : 6
homepage   : https://foss.heptapod.net/openpyxl
source     :
    - https://foss.heptapod.net/openpyxl/openpyxl/-/archive/3.0.10/openpyxl-3.0.10.tar.gz : a226ac5c3f1586f2131a8ebc99660ccbee75b7bc1985c0159e93a2da72703f97
license    : MIT
component  : programming.python
summary    : openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
description: |
    openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
builddeps  :
    - pkgconfig(python3)
    - python-et_xmlfile
    - python-jdcal
    - python-lxml
    - python-pillow
    - python-pytest
rundeps    :
    - python-et_xmlfile
    - python-jdcal
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
