name       : python-openpyxl
version    : 3.0.7
release    : 2
homepage   : https://foss.heptapod.net/openpyxl
source     :
    - https://foss.heptapod.net/openpyxl/openpyxl/-/archive/3.0.7/openpyxl-3.0.7.tar.gz : 9e4d563e98ce4b0f64beb7de29a9a4ddeac6c5aaf13bfef105c89611daae7b0f
license    : MIT
component  : programming.python
summary    : openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
description: |
    openpyxl is a Python library to read/write Excel 2010 xlsx/xlsm/xltx/xltm files.
builddeps  :
    - pkgconfig(python3)
    - python-et_xmlfile
    - python-jdcal
    - python-lxml
    - python-pillow
    - python-pytest
rundeps    :
    - python-et_xmlfile
    - python-jdcal
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3 -v
